name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
      - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
            os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Run check
      run: |
        make clean
        make check

    - name: Run test
      run: |
        make clean
        make test
